#!/usr/bin/env luajit
--[[--
Smoke test for EPUB Media Overlays generated by audiobookgen.
Verifies that epubmediaoverlay.lua accurately extracts OPF manifests, SMIL timings,
audio sources, and sentence text mappings from generated EPUBs.

Run from repo root:
  luajit dev/test_generated_epub_smil.lua
--]]

local RE_ANY_LAZY = "([%z\1-\255]-)"

local function escape_unzip_member(path)
    return path:gsub("%[", "[[]")
end

local function compact_xml(xml)
    if not xml or xml == "" then return xml end
    return xml:gsub(">%s+<", "><")
end

local function run_cmd(cmd)
    local h = io.popen(cmd .. " 2>&1")
    if not h then return nil end
    local out = h:read("*a") or ""
    h:close()
    return out
end

local function extract_from_zip(epub_path, internal_path)
    local zip_member = escape_unzip_member(internal_path)
    local cmd = string.format("unzip -p '%s' '%s'", epub_path:gsub("'", "'\\''"), zip_member:gsub("'", "'\\''"))
    return run_cmd(cmd)
end

local function parse_time_to_seconds(time_str)
    if not time_str then return 0 end
    time_str = time_str:gsub("^%s*", ""):gsub("%s*$", "")
    local hh, mm, ss = time_str:match("^(%d+):(%d+):([%d%.]+)$")
    if hh and mm and ss then
        return tonumber(hh) * 3600 + tonumber(mm) * 60 + tonumber(ss)
    end
    local mm2, ss2 = time_str:match("^(%d+):([%d%.]+)$")
    if mm2 and ss2 then
        return tonumber(mm2) * 60 + tonumber(ss2)
    end
    local secs = tonumber(time_str:match("^([%d%.]+)$"))
    if secs then return secs end
    return 0
end

local function parse_smil(smil_xml, audio_base)
    smil_xml = compact_xml(smil_xml)
    local timing_data = {}
    audio_base = audio_base or ""

    for _par_attrs, par_block in smil_xml:gmatch("<par([^>]*)>" .. RE_ANY_LAZY .. "</par>") do
        local text_src = par_block:match('<text[^>]-src%s*=%s*"([^"]+)"')
            or par_block:match('src%s*=%s*"([^"]+)"')
        local audio_block = par_block:match("<audio([^>]-)/>")
            or par_block:match("<audio" .. RE_ANY_LAZY .. "</audio>")

        if audio_block then
            local audio_src = audio_block:match('src%s*=%s*"([^"]+)"')
            local clip_begin = audio_block:match('clipBegin%s*=%s*"([^"]+)"')
            local clip_end = audio_block:match('clipEnd%s*=%s*"([^"]+)"')

            if audio_src then
                local resolved_audio = audio_src
                if audio_src:sub(1, 1) ~= "/" and audio_base ~= "" then
                    resolved_audio = audio_base .. "/" .. audio_src
                end
                local prev
                repeat
                    prev = resolved_audio
                    resolved_audio = resolved_audio:gsub("[^/]+/%.%./", "", 1)
                until resolved_audio == prev
                resolved_audio = resolved_audio:gsub("^%./", "")

                table.insert(timing_data, {
                    text = text_src or "",
                    text_ref = text_src,
                    audio_src = resolved_audio,
                    start_time = parse_time_to_seconds(clip_begin),
                    end_time = parse_time_to_seconds(clip_end),
                })
            end
        end
    end
    return timing_data
end

local function extract_sentence_texts(html)
    if not html or html == "" then return {} end
    local map = {}
    local stack = {}
    local i = 1
    local n = #html
    while i <= n do
        local s, e, attrs = html:find("<span([^>]*)>", i)
        local cs, ce = html:find("</span>", i)
        if s and (not cs or s < cs) then
            if s > i and #stack > 0 then
                table.insert(stack[#stack].parts, html:sub(i, s - 1))
            end
            local id = attrs and attrs:match('id%s*=%s*"([^"]+)"')
            table.insert(stack, { id = id, parts = {} })
            i = e + 1
        elseif cs then
            if cs > i and #stack > 0 then
                table.insert(stack[#stack].parts, html:sub(i, cs - 1))
            end
            local finished = table.remove(stack)
            i = ce + 1
            if finished then
                local body = table.concat(finished.parts)
                if #stack > 0 then
                    table.insert(stack[#stack].parts, body)
                end
                if finished.id and not map[finished.id] then
                    local txt = body:gsub("<[^>]->", "")
                        :gsub("&amp;", "&"):gsub("&lt;", "<"):gsub("&gt;", ">")
                        :gsub("&quot;", '"'):gsub("&#39;", "'"):gsub("&apos;", "'")
                        :gsub("&nbsp;", " "):gsub("&#160;", " ")
                        :gsub("%s+", " "):gsub("^%s+", ""):gsub("%s+$", "")
                    if txt ~= "" then map[finished.id] = txt end
                end
            end
        else
            if #stack > 0 and i <= n then
                table.insert(stack[#stack].parts, html:sub(i))
            end
            break
        end
    end
    return map
end

-- 1. Create a generated fixture EPUB using python helper if not already created
local fixture_epub = "dev/_fixtures/generated_test_audiobook.epub"
local make_cmd = "PYTHONPATH=. python3 -c \"from pathlib import Path; from tools.audiobookgen.tests.test_pipeline import create_sample_kepub, FakeTTSProvider; from tools.audiobookgen.pipeline.book import BookGenerationService; from tools.audiobookgen.pipeline.chapter import ChapterSynthesisService; from tools.audiobookgen.pipeline.cache import DiskSentenceCache; from tools.audiobookgen.models import VoiceProfile; from tools.audiobookgen.qc.retry import RetryPolicy; from tools.audiobookgen.qc.verifier import NullVerifier; p = Path('dev/_fixtures'); p.mkdir(parents=True, exist_ok=True); in_k = p / 'in.kepub'; out_e = p / 'generated_test_audiobook.epub'; create_sample_kepub(in_k); cache = DiskSentenceCache(p / 'work'); s = BookGenerationService(chapter_service=ChapterSynthesisService(tts_provider=FakeTTSProvider(), retry_policy=RetryPolicy(FakeTTSProvider(), NullVerifier(), 0), cache=cache), cache=cache); s.run(input_epub=in_k, output_epub=out_e, voice=VoiceProfile(), lang='da', resume=False)\""
run_cmd(make_cmd)

local failures = {}

-- 2. Inspect container.xml
local container = extract_from_zip(fixture_epub, "META-INF/container.xml")
if not container or container == "" then
    table.insert(failures, "missing META-INF/container.xml in generated EPUB")
end

local opf_path = container and container:match('full%-path%s*=%s*"([^"]+)"')
if not opf_path or opf_path == "" then
    table.insert(failures, "could not parse full-path in container.xml")
    opf_path = "OEBPS/content.opf"
end

-- 3. Inspect OPF
local opf = extract_from_zip(fixture_epub, opf_path)
if not opf or opf == "" then
    table.insert(failures, "could not read OPF file at " .. opf_path)
end

-- 4. Parse SMIL files and sentence texts
local smil1 = extract_from_zip(fixture_epub, "OEBPS/MediaOverlays/ch_001.smil")
if not smil1 or smil1 == "" then
    table.insert(failures, "missing OEBPS/MediaOverlays/ch_001.smil")
else
    local timings = parse_smil(smil1, "OEBPS/MediaOverlays")
    if #timings ~= 2 then
        table.insert(failures, "expected 2 timing entries in ch_001.smil, got " .. #timings)
    else
        if not timings[1].text_ref:find("#ch1_s1") then
            table.insert(failures, "timing 1 text_ref missing #ch1_s1: " .. tostring(timings[1].text_ref))
        end
        if timings[1].audio_src ~= "OEBPS/Audio/ch_001.mp3" then
            table.insert(failures, "unexpected resolved audio_src: " .. tostring(timings[1].audio_src))
        end
        if timings[1].start_time ~= 0.0 or timings[1].end_time <= 0.0 then
            table.insert(failures, "invalid timing interval: " .. timings[1].start_time .. " -> " .. timings[1].end_time)
        end
    end
end

local html1 = extract_from_zip(fixture_epub, "OEBPS/text/ch1.xhtml")
if not html1 or html1 == "" then
    table.insert(failures, "missing OEBPS/text/ch1.xhtml")
else
    local text_map = extract_sentence_texts(html1)
    if not text_map["ch1_s1"] then
        table.insert(failures, "missing sentence span id ch1_s1 in extracted text map")
    end
    if not text_map["ch1_s2"] then
        table.insert(failures, "missing sentence span id ch1_s2 in extracted text map")
    end
end

if #failures > 0 then
    io.stderr:write("FAIL: " .. #failures .. " errors in generated EPUB SMIL smoke test:\n")
    for _, msg in ipairs(failures) do
        io.stderr:write("  - " .. msg .. "\n")
    end
    os.exit(1)
end

print("ok: audiobookgen EPUB 3 Media Overlays smoke test passed successfully.")
